# substitution _PLUGIN_BUCKET,_MIG_REGION, _MIG_NAME
options:
  logging: CLOUD_LOGGING_ONLY

steps:

  - name: golang:1.20
    entrypoint: /bin/bash
    id: building plugins
    args:
      - -c
      - |
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

  - name: gcr.io/cloud-builders/gsutil
    entrypoint: /bin/bash
    id: updating plugins
    args:
      - -c
      - |

        result=$(gsutil -q stat gs://$_PLUGIN_BUCKET/api-plugins/versions.txt || echo 1)
        if [[ $result != 1 ]]; then
          echo "File exists"
          gsutil cp gs://$_PLUGIN_BUCKET/api-plugins/versions.txt versions.txt
        else
          echo "File does not exist"
          echo 1 > versions.txt
        fi

        

        echo $(($(cat versions.txt)+1)) > versions.txt
        
        gsutil cp dq-vault gs://$_PLUGIN_BUCKET/api-plugins/v$(cat versions.txt)
        gsutil cp versions.txt gs://$_PLUGIN_BUCKET/api-plugins/versions.txt

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: updating Migs
    entrypoint: gcloud
    args: ['compute', 'instance-groups', 'managed' ,'rolling-action', 'replace', '${_MIG_NAME}', '--region', '${_MIG_REGION}', '--max-surge','3']
